language: node_js
node_js:
  - 12
cache:
  directories:
    - front/node_modules
    - back/node_modules
jobs:
  include:
    - stage: backend install
      script:
        - cd back
        - npm install
    - stage: backend test
      script:
        - cd back
        - npm run check
        - npm run test
    - stage: backend integration
      script:
        - cd back
        - npm run integration:docker
    - stage: frontend install & build
      script:
        - cd front
        - npm install
        - npm run build
    - stage: frontend test
      script:
        - cd front
        - npm run lint
        - npm run test
