language: node_js
node_js:
  - 12
cache:
  directories:
    - front/node_modules
jobs:
  include:
    - stage: install & build
      script:
        - cd front
        - npm install
        - npm run build
    - stage: test
      script:
        - cd front
        - npm run lint
        - npm run test
