graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
spring:
  profiles:
    active: dev,init
server:
  port: 8080
logging:
  level:
    root: INFO
    fr.skilltrack.SkilltrackApplication: DEBUG

graphiql:
  mapping: /graphiql
  enabled: true
  pageTitle: SkillQL
  cdn:
    enabled: true
    version: 0.13.0