# docker-compose for test developpement
# don't deploy it in the production server
version: "3.7"

services:
  integration-db-test:
    image: mdillon/postgis
    ports:
      - 5435:5435
    environment:
      - POSTGRES_DB=polyconseil
      - POSTGRES_USER=polyconseil
      - POSTGRES_PASSWORD=polyconseil
    volumes:
      - ../init-db:/docker-entrypoint-initdb.d

  integration-back-test:
    build:
      context: .
      target: back-install
    env_file:
      - .env
    environment:
      - DB_HOST=integration-db-test
      - DB_PORT=5435
      - CI
    volumes:
      - ./reports:/app-build/reports
      - ./src:/ts-src/
    depends_on:
      - integration-db-test
